name = "Hugo Theme Bootie Docs"
license = "MIT"
licenselink = "https://github.com/cdpscc/hugo-theme-bootie-docs/LICENSE.md"
description = "A simple Hugo theme with Bootstrap for documentation"
homepage = "https://github.com/cdpscc/hugo-theme-bootie-docs"
tags = ["document", "bootstrap"]
features = ["document", ""]
min_version = 0.15

[author]
  name = "cdpscc"
  homepage = "https://cdpscc.github.io/"

# If porting an existing theme
[original]
  name = "Hugo Theme Bootie Docs"
  homepage = "http://key-amb.github.io/bootie-docs-demo/"
  repo = "https://github.com/key-amb/hugo-theme-bootie-docs"
